##### GPU-based EC2 instances ####
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu
spec:
  amiSelectorTerms: 
    - alias: al2023@latest
  role: ex-eks-gpu
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ex-eks-gpu
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ex-eks-gpu 
  tags:
    karpenter.sh/discovery: ex-eks-gpu
    environment: "dev"
    team: "platform"
---

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nvdia-gpu
spec:
  template:
    metadata:
      labels:
        nvidia.com/gpu.present: "true"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu

      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["g"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["g4dn", "g5"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["2xlarge", "4xlarge", "8xlarge"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand", "spot"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
      taints:
        - key: nvidia.com/gpu
          effect: NoSchedule
  limits:
    cpu: "80"
    memory: 128Gi

